<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="207edb8e-9869-41b4-9eb0-b0d2cc9b38af" name="Steve@STEVEIBPDESKTOP 2010-08-31 23:42:28" runUser="SteveIBPDesktop\Steve" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="35acf09e-fec5-4d96-8fa2-c858d3f35565">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="Steve_STEVEIBPDESKTOP 2010-08-31 23_42_28" />
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2010-08-31T23:42:28.0900625-04:00" queuing="2010-08-31T23:42:28.0959219-04:00" start="2010-08-31T23:42:28.1056875-04:00" finish="2010-08-31T23:42:30.7843984-04:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="NotFailWithNoItemsNotificationNoCreditCard" storage="c:\users\steve\documents\my projects\pluralsight\005 - dependency inversion principle\dip1\commerce\bin\debug\commerce.dll" id="987dbc40-e83f-b22f-fe88-6c2e28a35403">
      <Execution id="0a86c452-aacd-4b2d-8657-c469c68e4777" />
      <TestMethod codeBase="C:/Users/Steve/Documents/My Projects/PluralSight/005 - Dependency Inversion Principle/DIP1/Commerce/bin/Debug/Commerce.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="Commerce.OrderCheckoutShould, Commerce, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="NotFailWithNoItemsNotificationNoCreditCard" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="987dbc40-e83f-b22f-fe88-6c2e28a35403" executionId="0a86c452-aacd-4b2d-8657-c469c68e4777" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="0a86c452-aacd-4b2d-8657-c469c68e4777" testId="987dbc40-e83f-b22f-fe88-6c2e28a35403" testName="NotFailWithNoItemsNotificationNoCreditCard" computerName="STEVEIBPDESKTOP" duration="00:00:02.0486612" startTime="2010-08-31T23:42:28.1086172-04:00" endTime="2010-08-31T23:42:30.3605703-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="0a86c452-aacd-4b2d-8657-c469c68e4777">
      <Output>
        <ErrorInfo>
          <Message>Test method Commerce.OrderCheckoutShould.NotFailWithNoItemsNotificationNoCreditCard threw exception: 
System.Net.Mail.SmtpException: Failure sending mail. ---&gt; System.Net.WebException: Unable to connect to the remote server ---&gt; System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:25</Message>
          <StackTrace>    at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Int32 timeout, Exception&amp; exception)
 --- End of inner exception stack trace ---
    at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress&amp; address, Socket&amp; abortSocket, Socket&amp; abortSocket6, Int32 timeout)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, Int32 timeout, GeneralAsyncDelegate asyncCallback)
   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)
   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
 --- End of inner exception stack trace ---
    at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at Commerce.Model.Order.NotifyCustomer(Cart cart) in C:\Users\Steve\Documents\My Projects\PluralSight\005 - Dependency Inversion Principle\DIP1\Commerce\Model\Order.cs:line 43
   at Commerce.Model.Order.Checkout(Cart cart, PaymentDetails paymentDetails, Boolean notifyCustomer) in C:\Users\Steve\Documents\My Projects\PluralSight\005 - Dependency Inversion Principle\DIP1\Commerce\Model\Order.cs:line 21
   at Commerce.OrderCheckoutShould.NotFailWithNoItemsNotificationNoCreditCard() in C:\Users\Steve\Documents\My Projects\PluralSight\005 - Dependency Inversion Principle\DIP1\Commerce\CartShould.cs:line 34
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>